param(
    # Where the scenario files are written (the autopilot's scenario folder).
    [string] $OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'autopilot\scenarios'),
    [string] $Holsters = (Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'config\holsters.json'),
    # Fail (exit 1) instead of writing when a generated file differs from the file on disk.
    [switch] $Check
)

# Generates the T-044 review scenarios that repeat one block per outfit or per weapon pair:
#
#   stage1-loadout-outfits   every upper-body drawable Niko has (playerped.rpf uppr_000_u..uppr_016_u, found with
#                            `LibertyModel outfits`) wearing the same two long guns and a pistol: front, side and back
#                            screenshots, and a check that the holster module classified the outfit as config/holsters.json says.
#   stage1-loadout-review    every pair of Stage 1 long-gun classes (rifle + shotgun, SMG + rifle, SMG + shotgun) on the default
#                            and on a bulky outfit, from all sides.
#
# Outfit classes are read from the holsters config, so the expected class of every drawable can never drift from it.
$ErrorActionPreference = 'Stop'
$config = Get-Content -LiteralPath $Holsters -Raw | ConvertFrom-Json
$upperBodyComponent = 1
$upperBodyDrawables = 17
function Get-OutfitClass([int] $drawable) {
    foreach ($class in @($config.outfitClasses)) {
        if ([int]$class.component -eq $upperBodyComponent -and (@($class.drawables) -contains $drawable)) { return [string]$class.id }
    }
    return 'default'
}

$header = @(
    'events off',
    'await-alive 60000',
    'expect "autopilot_player_ready" 65',
    'god on',
    'wanted 0',
    'goto east_park',
    'expect "teleport_done id=east_park" 90',
    'wait 4000',
    'time 13 0',
    'wait 1500',
    'weather 1',
    'strip',
    'wait 1500'
)
function New-Loadout([int[]] $longGuns) {
    $lines = @()
    foreach ($id in $longGuns) { $lines += "give $id 100"; $lines += 'wait 1200' }
    $lines += 'give 7 100'
    $lines += 'wait 1500'
    $lines += 'holsters status'
    $lines += ('expect "holsters_status props=' + $longGuns.Count + ' existing=' + $longGuns.Count + ' slings=' + $longGuns.Count + ' slings_existing=' + $longGuns.Count + ' hidden=none" 10')
    return $lines
}
function New-Views([string] $name) {
    # Angle 0 is in front of Niko, 90 his side, 180 behind him (Autopilot `cam`).
    return @('cam 0 2.3 0.4', 'wait 1200', "shot ${name}_front", 'cam 90 2.1 0.4', 'wait 1200', "shot ${name}_side", 'cam 180 2.3 0.4', 'wait 1200', "shot ${name}_back")
}

# ---- outfits ----
$outfits = @('# T-044 clipping review per outfit: every upper-body drawable, rifle + shotgun slung, pistol holstered. Generated by')
$outfits += '# tools/perf/New-LoadoutScenarios.ps1; do not edit by hand. The class expected for each drawable comes from config/holsters.json.'
$outfits += $header
$outfits += New-Loadout @(14, 10)
$outfits += @('holsters outfits', 'hud off')
for ($drawable = 0; $drawable -lt $upperBodyDrawables; $drawable++) {
    $tag = '{0:D2}' -f $drawable
    $class = Get-OutfitClass $drawable
    $outfits += "# outfit $tag ($class)"
    $outfits += "holsters outfit $upperBodyComponent $drawable 0"
    $outfits += "expect `"holsters_outfit_set component=$upperBodyComponent requested=$drawable now=$drawable`" 10"
    $outfits += 'wait 1500'
    $outfits += 'holsters status'
    $outfits += "expect `"holsters_status props=2 existing=2 slings=2 slings_existing=2 hidden=none outfit=$class `" 10"
    $outfits += New-Views "outfit_$tag"
}
$outfits += @("holsters outfit restore", 'cam off', 'hud on', 'clear')

# ---- weapon classes ----
# Micro Uzi (12) is the SMG, AK-47 (14) the rifle, shotgun (10).
$pairs = @(
    @{ Name = 'rifle_shotgun'; Guns = @(14, 10) },
    @{ Name = 'smg_rifle'; Guns = @(12, 14) },
    @{ Name = 'smg_shotgun'; Guns = @(12, 10) }
)
$outfitSamples = @(@{ Name = 'default'; Drawable = 6 }, @{ Name = 'bulky'; Drawable = 3 })
$review = @('# T-044 clipping review per weapon class: each pair of Stage 1 long-gun classes on a slim and on a bulky outfit. Generated by')
$review += '# tools/perf/New-LoadoutScenarios.ps1; do not edit by hand.'
$review += $header
$review += 'hud off'
foreach ($pair in $pairs) {
    $review += "# $($pair.Name)"
    $review += 'strip'
    $review += 'wait 1500'
    $review += New-Loadout $pair.Guns
    foreach ($sample in $outfitSamples) {
        $review += "holsters outfit $upperBodyComponent $($sample.Drawable) 0"
        $review += "expect `"holsters_outfit_set component=$upperBodyComponent requested=$($sample.Drawable) now=$($sample.Drawable)`" 10"
        $review += 'wait 1500'
        $review += New-Views "$($pair.Name)_$($sample.Name)"
    }
}
$review += @('holsters outfit restore', 'cam off', 'hud on', 'clear')

$failed = $false
foreach ($file in @(@{ Name = 'stage1-loadout-outfits.txt'; Lines = $outfits }, @{ Name = 'stage1-loadout-review.txt'; Lines = $review })) {
    $path = Join-Path $OutputDirectory $file.Name
    $text = (($file.Lines -join "`n") + "`n")
    if ($Check) {
        $onDisk = if (Test-Path -LiteralPath $path) { ([IO.File]::ReadAllText($path)) -replace "`r`n", "`n" } else { $null }
        if ($onDisk -ne $text) { Write-Host "OUT OF DATE: $($file.Name) (run tools/perf/New-LoadoutScenarios.ps1)"; $failed = $true }
    }
    else {
        [IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding($false)))
        Write-Host "wrote $path"
    }
}
if ($failed) { exit 1 }
