param(
    # Where the scenario files are written (the autopilot's scenario folder).
    [string] $OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'autopilot\scenarios'),
    # config/devtools/locations.json: the capture points are its "s1_*" entries, in file order.
    [string] $Locations = (Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'config\devtools\locations.json'),
    # Fail (exit 1) instead of writing when a generated file differs from the file on disk (used by the offline checks).
    [switch] $Check
)

# Generates the Stage 1 measurement scenarios (T-040) from the capture points in config/devtools/locations.json, so the
# scenario files and the points can never drift apart. The scenarios are plain autopilot scripts (tools/autopilot/Run-Scenario.ps1);
# tools/perf/Measure-Stage1.ps1 turns their reports into the JSON summary.
#
#   stage1-capture-broker / stage1-capture-city          the mod-on capture points (8 Broker/Dukes, 4 elsewhere)
#   stage1-capture-broker-off / stage1-capture-city-off  the same with the Liberty gameplay modules stopped (mod-off)
#
# Per point: teleport, wait for streaming, then two conditions (day 13:00 overcast, night 23:00 rain). Each condition
# settles, resets the frame statistics and cost meter, samples for a fixed window, then records perf, frame statistics,
# per-section costs, pools and GPU memory, and only then takes the screenshot (the F12 capture hitches, so it must not
# sit inside the sample window).
$ErrorActionPreference = 'Stop'

# GTA IV weather ids used by the autopilot's `weather`: 0 extra sunny, 1 sunny, 2 sunny windy, 3 cloudy (overcast),
# 4 rain, 5 drizzle, 6 foggy, 7 lightning.
$conditions = @(
    @{ Name = 'day';   Hour = 13; Weather = 3; Text = 'day 13:00 overcast' },
    @{ Name = 'night'; Hour = 23; Weather = 4; Text = 'night 23:00 rain' }
)
$streamingWaitMs = 8000
$settleMs = 5000
$sampleMs = 8000

# The Liberty gameplay modules stopped for the mod-off runs. devtools stays (it owns `goto`), the engine, watchdog and
# autopilot stay (they are the measurement), the world mod places props only. Restarted at the end so the next
# scenario in the same game session is mod-on again.
$gameplayModules = @('gunplay', 'combat', 'arsenal', 'holsters', 'atmosphere')

# A dead or respawning player cannot be teleported: wait for a live one, then make the run safe and quiet.
function New-Setup {
    return @('await-alive 60000', 'expect "autopilot_player_ready" 65', 'events off', 'god on', 'wanted 0')
}

function New-ModOffPrelude {
    $lines = @('# Mod-off: the Liberty gameplay modules are stopped (each restores the game''s own behaviour and the player''s settings).')
    foreach ($module in $gameplayModules) { $lines += "stop $module" }
    $lines += 'modules'
    $lines += 'expect "line=.modules. reply=.*gunplay\(off.*combat\(off.*arsenal\(off.*holsters\(off.*atmosphere\(off" 10'
    return $lines
}

function New-ModOffEpilogue {
    # holsters requires arsenal: restart in dependency order, each one by itself (restart only revives what was running).
    $lines = @('# Back to mod-on for whatever runs next in this game session.')
    foreach ($module in $gameplayModules) { $lines += "restart $module" }
    $lines += 'modules'
    $lines += 'expect "line=.modules. reply=.((?!\(off:).)*$" 10'
    return $lines
}

function New-CaptureScenario([string] $Title, [object[]] $Points, [bool] $ModOff) {
    $lines = New-Object System.Collections.Generic.List[string]
    $mode = if ($ModOff) { 'mod-off' } else { 'mod-on' }
    $lines.Add("# $Title ($mode). Generated by tools/perf/New-Stage1Scenarios.ps1 from config/devtools/locations.json; do not edit by hand.")
    $lines.Add('# Per point and condition: label, sample window (frame statistics, costs), perf, pools, GPU memory, then a clean screenshot.')
    $lines.Add('# tools/perf/Measure-Stage1.ps1 summarises the report folder.')
    foreach ($l in (New-Setup)) { $lines.Add($l) }
    if ($ModOff) { foreach ($l in (New-ModOffPrelude)) { $lines.Add($l) } } else { $lines.Add('modules') }
    foreach ($point in $Points) {
        $lines.Add('')
        $lines.Add("# $($point.name)")
        $lines.Add("goto $($point.id)")
        # The teleport blocks in LOAD_SCENE (4 to 18 s measured) and logs teleport_done about a second later.
        $lines.Add("expect `"teleport_done id=$($point.id)`" 90")
        # Algonquin, Bohan and Alderney can raise a wanted level for an armed player on a locked island: clear it.
        $lines.Add('wanted 0')
        # Alderney streams in slowly on the hard disk (a 9 s LOAD_SCENE and the road surface still missing 14 s later).
        $lines.Add("wait $(if ($point.id -eq 's1_alderney_city') { $streamingWaitMs * 3 } else { $streamingWaitMs })")
        foreach ($condition in $conditions) {
            $label = "$($point.id)_$($condition.Name)"
            # Clock first, weather after a pause: the weather director (atmosphere module) counts an hour change and may
            # replace the weather within a second of it, which would leave the wrong weather in the sample.
            $lines.Add("time $($condition.Hour) 0")
            $lines.Add('wait 1500')
            $lines.Add("weather $($condition.Weather)")
            $lines.Add("wait $settleMs")
            $lines.Add("label $label")
            # PC load at both ends of the window: hitches caused by something else touching the disk show up here.
            $lines.Add("gpumem ${label}_start")
            $lines.Add('framestats')
            $lines.Add('costs')
            $lines.Add("wait $sampleMs")
            $lines.Add('perf')
            $lines.Add('framestats')
            $lines.Add('costs')
            $lines.Add('pools')
            $lines.Add("gpumem $label")
            $lines.Add('hud off')
            $lines.Add("shot $label")
            $lines.Add('hud on')
        }
    }
    if ($ModOff) { $lines.Add(''); foreach ($l in (New-ModOffEpilogue)) { $lines.Add($l) } }
    return $lines
}

# The worst-case scene (STAGE1 section 10, Pillar 5): Broker/Dukes, night, rain, ambient traffic and pedestrians at the
# game's own density, a firefight (12 armed subjects fighting in pairs, 25 more pedestrians around them), blood and
# effects active, the HUD on. One 60 s sample: frame statistics over the whole window, costs and GPU memory every 10 s.
function New-WorstCaseScenario([bool] $ModOff) {
    $lines = New-Object System.Collections.Generic.List[string]
    $mode = if ($ModOff) { 'mod-off' } else { 'mod-on' }
    $lines.Add("# Stage 1 worst-case scene ($mode): Hove Beach, night 23:00, rain, ambient traffic and pedestrians, a firefight, blood and effects, HUD on.")
    $lines.Add('# Generated by tools/perf/New-Stage1Scenarios.ps1; do not edit by hand. One 60 s window (label worst_case).')
    foreach ($l in (New-Setup)) { $lines.Add($l) }
    if ($ModOff) { foreach ($l in (New-ModOffPrelude)) { $lines.Add($l) } } else { $lines.Add('modules') }
    $lines.Add('goto s1_hove_beach_a')
    $lines.Add('expect "teleport_done id=s1_hove_beach_a" 90')
    $lines.Add('wait 10000')
    $lines.Add('time 23 0')
    $lines.Add('wait 1500')
    $lines.Add('weather 4')
    $lines.Add('give 14 300')
    $lines.Add('wait 8000')
    $lines.Add('# Combat: 12 pistol subjects in 6 pairs, 25 unarmed pedestrians around them.')
    $lines.Add('spawn 12 12 7')
    $lines.Add('wait 6000')
    $lines.Add('stress 25')
    $lines.Add('wait 4000')
    $lines.Add('label worst_case')
    $lines.Add('framestats')
    # (worst_case_00 below is the first PC-load sample; the others follow every 10 s)
    $lines.Add('costs')
    $lines.Add('gpumem worst_case_00')
    $lines.Add('fight 0 1')
    $lines.Add('fight 2 3')
    $lines.Add('fight 4 5')
    $lines.Add('fight 6 7')
    $lines.Add('fight 8 9')
    $lines.Add('fight 10 11')
    $lines.Add('pfire near 5000')
    for ($second = 10; $second -le 60; $second += 10) {
        $lines.Add('wait 10000')
        $lines.Add('perf')
        $lines.Add('costs')
        $lines.Add('pools')
        $lines.Add('gpumem worst_case_' + $second.ToString('00'))
        # Keep the shooting going: subjects still standing fire again, the survivors of the pairs keep fighting, and the
        # player shoots the nearest subject (only the player's violence reaches the gore and effect modules).
        if ($second -lt 60) { $lines.Add('fire all 4000'); $lines.Add('pfire near 4000') }
        if ($second -eq 30) { $lines.Add('shot worst_case_mid') }
    }
    $lines.Add('framestats')
    $lines.Add('modules')
    $lines.Add('shot worst_case_end')
    $lines.Add('clear')
    $lines.Add('status')
    if ($ModOff) { $lines.Add(''); foreach ($l in (New-ModOffEpilogue)) { $lines.Add($l) } }
    return $lines
}

$file = Get-Content -LiteralPath $Locations -Raw | ConvertFrom-Json
$points = @($file.locations | Where-Object { $_.id -like 's1_*' })
if ($points.Count -ne 12) { throw "expected 12 s1_* capture points in $Locations, found $($points.Count)" }
$broker = @($points | Select-Object -First 8)
$city = @($points | Select-Object -Skip 8)

$outputs = [ordered]@{
    'stage1-capture-broker'     = New-CaptureScenario 'Stage 1 capture: the 8 Broker/Dukes points' $broker $false
    'stage1-capture-city'       = New-CaptureScenario 'Stage 1 capture: the 4 points elsewhere in the city' $city $false
    'stage1-capture-broker-off' = New-CaptureScenario 'Stage 1 capture: the 8 Broker/Dukes points' $broker $true
    'stage1-capture-city-off'   = New-CaptureScenario 'Stage 1 capture: the 4 points elsewhere in the city' $city $true
    'stage1-worst-case'         = New-WorstCaseScenario $false
    'stage1-worst-case-off'     = New-WorstCaseScenario $true
}

$stale = @()
foreach ($name in $outputs.Keys) {
    $path = Join-Path $OutputDirectory ($name + '.txt')
    $text = (($outputs[$name] -join "`n") + "`n")
    if ($Check) {
        $existing = if (Test-Path -LiteralPath $path) { (Get-Content -LiteralPath $path -Raw) -replace "`r`n", "`n" } else { '' }
        if ($existing -ne $text) { $stale += $name }
    }
    else { [IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding($false))); Write-Host "wrote $path" }
}
if ($Check) {
    if ($stale.Count -gt 0) { Write-Host "stale scenarios (run tools/perf/New-Stage1Scenarios.ps1): $($stale -join ', ')"; exit 1 }
    Write-Host "Stage 1 scenarios are up to date ($($outputs.Count) files)"
}
