"""Builds config/impact-surfaces.json from the installed materials.dat (T-050, for lane C's per-surface impact effects).

Usage: python tools/research/build_impact_surfaces.py "<GTAIV dir>"
The hit's `material_id` (RayHit.SurfaceMaterialId) is the 0-based index of a data row in common/data/materials/materials.dat
(blank and '#' lines skipped, the first line is the version). The file's SHA-256 is stored so a consumer can refuse a
materials.dat that differs from the one the table was built for. Impact classes are the effect-name suffixes lane C accepts.
"""
import hashlib, json, os, sys

GROUP_CLASS = {
    'CONCRETE': 'concrete', 'STONE': 'concrete', 'BRICK_COBBLE': 'concrete', 'MARBLE': 'concrete',
    'PAVING_SLABS': 'concrete', 'CERAMICS': 'concrete',
    'WOOD': 'wood', 'LAMINATE': 'wood', 'TREE_BARK_DARK': 'wood', 'TREE_BARK_LIGHT': 'wood', 'TREE_BARK_MEDIUM': 'wood',
    'METAL': 'metal', 'CAR_METAL': 'metal',
    'GLASS': 'glass', 'WINDSCREEN': 'glass', 'TVSCREEN': 'glass', 'VIDEOWALL': 'glass',
    'PED_TORSO': 'ped', 'PED_LIMB': 'ped', 'PED_HEAD': 'ped', 'PED_FOOT': 'ped',
}

def main(game):
    path = os.path.join(game, 'common', 'data', 'materials', 'materials.dat')
    raw = open(path, 'rb').read()
    lines = [l for l in raw.decode('latin-1').splitlines() if l.strip() and not l.lstrip().startswith('#')]
    rows = []
    for index, line in enumerate(lines[1:]):
        cols = line.split()
        name, group = cols[0], cols[1]
        impact = GROUP_CLASS.get(group, 'default')
        rows.append({'id': index, 'name': name, 'group': group, 'impact': impact, 'water': group == 'WATER'})
    out = {
        'comment': 'Generated by tools/research/build_impact_surfaces.py. id = 0-based data row of materials.dat. impact is default for every group not listed in groupToImpact; ped rows are not surface impacts (gore handles them, and armour is chosen from the ped state, not from a material).',
        'materialsDatSha256': hashlib.sha256(raw).hexdigest().upper(),
        'rowCount': len(rows),
        'impactClasses': ['concrete', 'wood', 'metal', 'glass', 'default'],
        'groupToImpact': GROUP_CLASS,
        'rows': rows,
    }
    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'config', 'impact-surfaces.json')
    open(target, 'wb').write((json.dumps(out, indent=1) + '\n').encode('utf-8'))
    counts = {}
    for r in rows: counts[r['impact']] = counts.get(r['impact'], 0) + 1
    print('rows', len(rows), counts, out['materialsDatSha256'])

main(sys.argv[1])
