using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using LibertyFramework.Finishes;

namespace LibertyFramework.Vehicles
{
    // T-023: reads every vehicle fragment (.wft) in the player's own pc/models/cdimages/vehicles.img and
    // records each "extra_N" part: its parent bone and its position in the car (from the skeleton's bone
    // records: +0x00 name, +0x10 parent, +0x60 model-space position). A body-part label is derived from
    // that geometry, so the LVS workshop can name what an extra actually is. Nothing from the game is
    // shipped; the generated JSON lives in staging and is installed as config.
    internal static class VehicleExtrasScanner
    {
        private const uint SystemBase = 0x50000000;

        internal static int Run(string[] args)
        {
            if (args.Length < 2) { Console.WriteLine("usage: VehicleExtras <game directory> <output json>"); return 2; }
            try
            {
                string game = args[0];
                byte[] key = ImgArchive.FindKey(Path.Combine(game, "GTAIV.exe"));
                ImgArchive img = ImgArchive.Open(Path.Combine(game, @"pc\models\cdimages\vehicles.img"), key);
                StringBuilder json = new StringBuilder();
                json.Append("{\n  \"schemaVersion\": 1,\n  \"source\": \"pc/models/cdimages/vehicles.img (generated by tools/vehicles)\",\n  \"vehicles\": [\n");
                int models = 0, extras = 0;
                bool first = true;
                foreach (ImgArchive.Entry entry in img.Entries)
                {
 string name = entry.Name;
                    if (!name.EndsWith(".wft", StringComparison.OrdinalIgnoreCase)) { continue; }
                    string model = name.Substring(0, name.Length - 4).ToLowerInvariant();
                    byte[] body;
                    try { body = RscResource.Parse(img.Extract(name)).Body; }
                    catch (Exception error) { Console.WriteLine("  skip " + name + ": " + error.Message); continue; }
                    List<string> parts = ScanExtras(body);
                    if (parts.Count == 0) { continue; }
                    models++; extras += parts.Count;
                    if (!first) { json.Append(",\n"); }
                    first = false;
                    json.Append("    { \"model\": \"" + model + "\", \"modelHash\": " + ModelHash(model).ToString(CultureInfo.InvariantCulture) +
                        ", \"extras\": [\n      " + string.Join(",\n      ", parts.ToArray()) + "\n    ] }");
                }
                json.Append("\n  ]\n}\n");
                File.WriteAllText(args[1], json.ToString(), new UTF8Encoding(false));
                Console.WriteLine("vehicle extras: models=" + models + " extras=" + extras + " -> " + args[1]);
                return models > 0 ? 0 : 1;
            }
            catch (Exception error)
            {
                Console.WriteLine("FAILED " + error);
                return 1;
            }
        }

        internal static List<string> ScanExtras(byte[] body)
        {
            List<string> result = new List<string>();
            HashSet<int> seen = new HashSet<int>();
            foreach (Match match in Regex.Matches(Encoding.ASCII.GetString(body), "extra_([0-9]{1,2})\0"))
            {
                int index = int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
                uint pointer = SystemBase + (uint)match.Index;
                for (int offset = 0; offset + 0x70 <= body.Length; offset += 16)
                {
                    if (BitConverter.ToUInt32(body, offset) != pointer) { continue; }
                    string parent = ParentName(body, BitConverter.ToUInt32(body, offset + 0x10));
                    if (parent == null) { continue; }
                    float x = BitConverter.ToSingle(body, offset + 0x60), y = BitConverter.ToSingle(body, offset + 0x64), z = BitConverter.ToSingle(body, offset + 0x68);
                    if (float.IsNaN(x) || Math.Abs(x) > 10 || Math.Abs(y) > 20 || Math.Abs(z) > 10) { continue; }
                    if (!seen.Add(index)) { break; }
                    result.Add("{ \"extra\": " + index + ", \"parent\": \"" + parent + "\", \"x\": " + F(x) + ", \"y\": " + F(y) + ", \"z\": " + F(z) +
                        ", \"label\": \"" + Label(parent, x, y, z) + "\" }");
                    break;
                }
            }
            result.Sort(StringComparer.Ordinal);
            return result;
        }

        // Parent pointer must reference another bone record whose first field is a name pointer.
        private static string ParentName(byte[] body, uint pointer)
        {
            if (pointer < SystemBase || pointer - SystemBase + 4 > body.Length) { return null; }
            uint name = BitConverter.ToUInt32(body, (int)(pointer - SystemBase));
            if (name < SystemBase || name - SystemBase >= body.Length) { return null; }
            int start = (int)(name - SystemBase), end = start;
            while (end < body.Length && end - start < 32 && body[end] >= 0x20 && body[end] < 0x7F) { end++; }
            if (end == start || end >= body.Length || body[end] != 0) { return null; }
            return Encoding.ASCII.GetString(body, start, end - start);
        }

        // Geometry-based naming (car space: +y forward, +z up). Parent bones win when they are body panels.
        internal static string Label(string parent, float x, float y, float z)
        {
            switch (parent)
            {
                case "bonnet": return "Hood scoop / hood panel";
                case "boot": return "Trunk spoiler / boot panel";
                case "bumper_f": return "Front bumper part";
                case "bumper_r": return "Rear bumper part";
                case "door_dside_f": case "door_pside_f": case "door_dside_r": case "door_pside_r": return "Door part";
            }
            // Bone at the car origin: the part's position is baked into its mesh, so geometry cannot name it.
            if (Math.Abs(x) < 0.01f && Math.Abs(y) < 0.01f && Math.Abs(z) < 0.01f) { return "Body part"; }
            if (z > 0.75f && Math.Abs(y) < 1.2f) { return "Roof item (rack, sign or light)"; }
            if (y < -1.0f && z > 0.3f) { return "Rear spoiler / wing"; }
            if (z < -0.2f) { return "Lower trim / underbody"; }
            if (y > 1.2f && z < 0.35f) { return "Front bumper part"; }
            if (y < -1.2f) { return "Rear bumper part"; }
            if (Math.Abs(x) > 0.7f) { return "Side part"; }
            return "Body part";
        }

        private static string F(float value) { return value.ToString("0.###", CultureInfo.InvariantCulture); }

        // GTA IV model hashes are Jenkins one-at-a-time of the lower-case model name.
        internal static int ModelHash(string name)
        {
            uint hash = 0;
            foreach (char character in name.ToLowerInvariant())
            {
                hash = unchecked(hash + (byte)character); hash = unchecked(hash + (hash << 10)); hash ^= hash >> 6;
            }
            hash = unchecked(hash + (hash << 3)); hash ^= hash >> 11; hash = unchecked(hash + (hash << 15));
            return unchecked((int)hash);
        }
    }
}
